### ISSUE TITLE
I want to support micromdm How to start kmfddm

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [jessepeterson/kmfddm#60]
I want to support micromdm How to start kmfddm

**Comment by jessepeterson** [comment]
Follow along with the Guide: https://github.com/jessepeterson/kmfddm/blob/main/docs/quickstart.md :) 

Instead of starting NanoMDM, use the `-dm` switch to MicroMDM.

**Comment by zxyzhouxiaoyun** [comment]
> Follow along with the Guide: https://github.com/jessepeterson/kmfddm/blob/main/docs/quickstart.md :)
> 
> Instead of starting NanoMDM, use the `-dm` switch to MicroMDM.

-enqueue-key   What should I fill in for this parameter?

**Comment by jessepeterson** [comment]
> -enqueue-key -enqueue What should I fill in for this parameter?

These are the API key for MicroMDM and the API URL for submitting commands: usually `/v1/commands` of your MicroMDM server.

**Comment by zxyzhouxiaoyun** [comment]
> > -enqueue-key -enqueue What should I fill in for this parameter?
> 
> These are the API key for MicroMDM and the API URL for submitting commands: usually `/v1/commands` of your MicroMDM server.

thank you
